### PR TITLE
completed Design 1 - Please Review

### PR DESCRIPTION
**Pull request by Reethuch**

### CODE REVIEW

**Review by daredevilteja — COMMENTED** [review]
SC is O(n)

**Comment by daredevilteja** [comment]
Good Work! Keep it up.

**Comment by Reethuch** [comment]
> SC is O(n)
Thank you Teja.
For both the questions, the space  complexity is O(n) right?

**Comment by daredevilteja** [comment]
> > SC is O(n)
> > Thank you Teja.
> > For both the questions, the space  complexity is O(n) right?

Yes

**Pull request closed without merging**
